propeller-heads/tycho-indexer

tycho-indexer/src/services/deltas_buffer.rs, tycho-indexer/src/services/rpc.rs
This PR fixes request that specify the version using a block hash. 
In the current code this would fail if the requested block was recent and still stored in the buffer.
Proposed solution: if the hash isn't found in the db, also search for it in the buffer. Then if it's not found in the buffer either, return the block not found error.
=> fix(rpc): add buffer lookup for version given as block hash

Cargo.lock, Cargo.toml, tycho-indexer/Cargo.toml, tycho-indexer/src/main.rs
Set up a global metrics exporter and expose /metrics endpoint.
=> feat: set up metrics exporter

tycho-indexer/src/extractor/protocol_extractor.rs, tycho-indexer/src/extractor/runner.rs, tycho-indexer/src/services/rpc.rs, tycho-indexer/src/services/ws.rs
And fix typo in the protocol_components endpoint metric
=> fix: split chain and extractor metric labels

tycho-storage/src/postgres/contract.rs, tycho-storage/src/postgres/protocol.rs
Add tracing spans for 'get' methods on the postgres gateway.
=> fix: add more db gateway 'get' tracing spans

proto/README.md, proto/tycho/evm/v1/common.proto, tycho-indexer/src/pb/testing.rs, tycho-indexer/src/pb/tycho.evm.v1.rs
Not sure why there are all those formatting changes to the generated protobuf file. I found the PR where the protobuf formatting check was added to CI and followed the instructions there to lint the file.
=> feat: add AccountBalances to the protobuf messages

tycho-core/src/dto.rs
for simpler conversions in external projects
=> fix: update ChangeType enum derived traits

tycho-indexer/src/services/rpc.rs
Currently, the order of tokens is random — it depends on how the tokens were inserted into our database. This commit aims to make the order consistent when returning data in our RPC.
=> feat(rpc): sort tokens by address in `get_protocol_component`

tycho-storage/src/postgres/protocol.rs
Performance improvement: using EXISTS instead of `eq_any` shows significant performance improvements during tests.
=> fix: improve efficiency of activity filter on tokens query

tycho-indexer/src/extractor/protocol_extractor.rs
Currently it panics if the conversion to minute fails. This commit makes it just skip the report and log a warning instead.
=> refactor(indexer): better error handling in `maybe_report_progress`

tycho-indexer/src/main.rs
This update improves the shutdown process by adding support for SIGTERM signals.
This is needed to properly terminate the pod in Kubernetes. Currently it only ends when Kubernetes sends the `SIGKILL` after waiting 30 secs.
=> feat: enhance shutdown handling with SIGTERM support

tycho-indexer/src/substreams/stream.rs
This is needed so we don't flood them on error. We recently experienced this.
=> fix: add backoff for retries on connections error with Substreams

tycho-indexer/src/extractor/runner.rs
Currently we're only exiting the loop on `Err`, but the Stop signal doesn't produce an `Err` but a `Ok(())`. This means the extraction continue even after receiving a Stop signal. This commit fixes this.
=> fix: correctly exit extraction loop on stop signal

tycho-client/src/cli.rs, tycho-client/src/feed/synchronizer.rs, tycho-client/src/rpc.rs, tycho-client/src/stream.rs, tycho-common/src/dto.rs, tycho-common/src/storage.rs, tycho-indexer/src/services/mod.rs, tycho-indexer/src/services/rpc.rs, tycho-indexer/src/testing.rs, tycho-storage/src/postgres/cache.rs, tycho-storage/src/postgres/protocol.rs
Close https://github.com/propeller-heads/tycho-indexer/issues/532
=> feat: add component tvl

tycho-indexer/src/extractor/dynamic_contract_indexer.rs, tycho-indexer/src/extractor/protobuf_deserialisation.rs, tycho-indexer/src/extractor/protocol_extractor.rs, tycho-indexer/src/extractor/runner.rs, tycho-indexer/src/main.rs, tycho-storage/src/postgres/contract.rs, tycho-storage/src/postgres/entry_point.rs, tycho-storage/src/postgres/orm.rs
This PR fixes many bugs that appeared when testing DCI release with Balancer V2 integration.
For more details on each bugs please check commits descriptions.
=> fix: miscellaneous fixes after DCI testing with Balancer V2

tycho-client/src/feed/mod.rs, tycho-client/src/feed/synchronizer.rs, tycho-storage/migrations/2023-08-15-154244_tycho_initial_setup/up.sql, tycho-storage/migrations/2024-09-4_v0.15.1/down.sql, tycho-storage/src/postgres/contract.rs
Marked as a refactor to trigger a new release
=> refactor: improve typos and grammar

tycho-indexer/src/extractor/dynamic_contract_indexer/cache.rs
There was a bug that was removing the wrong layers on revert. This was causing Tycho to panic with `DCICacheError::UnexpectedBlockOrder` because the wrong layers were left after a revert. So we were not expecting the right block on the next insert after a revert.
=> fix: correctly handle reverts in DCI cache

tycho-client/src/stream.rs
Reverts propeller-heads/tycho-indexer#621
=> fix: Revert: "fix: Correctly set Url scheme in TychoStreamBuilder"

tycho-common/src/models/protocol.rs, tycho-common/src/simulation/indicatively_priced.rs, tycho-common/src/simulation/mod.rs
Add GetAmountOutParams to models as well
=> feat: Add IndicativelyPriced trait

tycho-storage/migrations/2025-07-21_index_protocol_components/down.sql, tycho-storage/migrations/2025-07-21_index_protocol_components/notes.md, tycho-storage/migrations/2025-07-21_index_protocol_components/up.sql
This commit introduces new SQL migration files to create indexes that enhance query performance for protocol components.
=> refactor: optimize database performance with new indexes

tycho-indexer/src/services/ws.rs
**Problem**: WebSocket subscriptions were deadlocking when multiple clients subscribed simultaneously, causing timeouts and blocking the entire runtime.
**Root Cause**: block_on() called while holding a mutex in Actix actor context, which blocks the async runtime thread and prevents other actors from processing messages.
**Solution**:
1. Replace blocking with async spawning - Use ctx.spawn() instead of block_on() to prevent runtime blocking
2. Eliminate mutex entirely - Since subscribers map is read-only after startup, replace Arc<Mutex<HashMap>> with Arc<HashMap> for direct access
Test Coverage: Added comprehensive deadlock reproduction test with SlowMessageSender that simulates the original issue.
This fixes the production deadlock while providing significant performance improvements …
=> fix: Websocket deadlocks

tycho-client/src/deltas.rs
The WsDeltasClient assumed an infinite reconnection loop although later a max_reconnect_attempts was introduced to avoid spamming the server with reconnects. Unfortunately subscribe and unsubscribe would wrongly wait indefinitely until the connection is reestablished.
This fix introduced a simple flag to mark a client as dead and return an error if we try to subscribe on a client that maxed out it's reconnections attempts.
=> fix: WsDeltas client forever blocking subscribe.

tycho-ethereum/src/account_extractor/contract.rs
Added a debug mode to log raw JSON responses for easier troubleshooting of deserialization errors.
=> feat: Enhance storage response handling in EVMBatchAccountExtractor

tycho-ethereum/src/token_analyzer/trace_call.rs
Alloy `U256::from_be_bytes` is expecting a [u8; 32] but we were not padding the balances before so it was failing in the conversion.
=> fix: correctly parse token balances in token-analyzer
