propeller-heads/tycho-indexer

- tycho-client/src/feed/mod.rs
- tycho-client/src/feed/synchronizer.rs
Since the client constructs the FeedMsg, this was previously not required but allowing deserialization is extremely helpful for test assets.
> feat: Allow FeedMsg to be deserialized.

- tycho-storage/sql_scripts/prune_transaction_table.sql
This commits removes unnecessary constraint renaming, `transaction_hash_block_id_key` doesn't exist anymore.
> fix: update SQL script to prune `transaction` table

- tycho-client/src/feed/synchronizer.rs
With the smaller chunksize we were more likely to hit our rate limits. We still need to look into long term solutions to all the queries we need to do on start-up. For now this will be sufficient enough for the number of protocols and pools we have.
> feat(tycho-client): increase pagination chunksize to 100

- tycho-indexer/src/services/ws.rs
With this we will be able to track the following:
- the active websocket connections as well as which tycho-client version they use and what api_key they use (to group connections by user)
- the active exchange subscriptions so that we can see which protocols are actively being streamed
Design decision: we use the **gauge** metric to track which connections/subscriptions are active. We use the id to label the connection/subscription as the id is known at the time of disconnect and can be used to properly update the metric to reflect which connection/subscription ended.
We use the **counter** metric to link metadata to the id labeled in the 'active' connections gauge. This allows us to report info that is not known at the time of disconnect (only id is known there) and on our dashboard it …
> fix: improve websocket metrics with extended metadata

- tycho-indexer/src/services/ws.rs
Previously we would only decrement the active subscriptions if it was explicitly unsubscribed. We want to also decrement it on suddenly closed connections
> fix: decrement active subscription on ws connection close

- tycho-indexer/src/substreams/stream.rs
The block ts is still in seconds, however we can at least be more accurate with the current timestamp in our calculations to partially remove the inaccuracies of the metric.
> fix: calculate substream lag in millis

- tycho-indexer/src/services/ws.rs
Added user identity (a new header added during connection authentication) to ws connection metrics. This will allow us to monitor:
- how many connections each user has active
- what version client they're using
- which protocols they have active subscriptions to
This is to give us insight as to how tycho is currently being used as well as allow us to provide smoother easier support to our clients.
> feat: add user identity to ws connection metrics

- tycho-storage/sql_scripts/remove_protocol_system.sh
Context: in the tycho database schema, we use `accounts` for both token contracts and vm pool contracts. When we use the account as a token, we do not track balances of the account. When we use it as a pool, we do track balances (specifically eth balances) and store them in account_balance. 
Issue: In some special cases the same contract acts as both a pool and a token. Currently, when we delete a protocol where the account is used as a pool, we cascade delete the balances associated with it. However if the account is also used as a token outside of the protocol, we cannot delete the account and so the balances remain as well. This causes issues later if we resync the protocol that was deleted as the account balances already exist and cannot be re-created (only updated).
Solution: The …
> fix: fix protocol system deletion script account balances bug

- tycho-client/src/feed/synchronizer.rs
- tycho-client/src/rpc.rs
- tycho-core/src/dto.rs
- tycho-core/src/storage.rs
- tycho-indexer/src/services/mod.rs
- tycho-indexer/src/services/rpc.rs
- tycho-indexer/src/testing.rs
- tycho-storage/src/postgres/cache.rs
- tycho-storage/src/postgres/mod.rs
- tycho-storage/src/postgres/protocol.rs
This PR adds a new `GET /v1/protocol_systems` endpoint to fetch supported protocol systems in real time, using the existing cache and supports pagination with page and page_size.
The `chain` parameter is currently unused because protocol systems are not linked to specific chains in the cache or database. The association between protocol_systems and chain can be added in a follow-up PR when needed.
Unit tests and documentation updates are included.
Close #478
> feat: add protocol system rpc

- Cargo.lock
- tycho-indexer/Cargo.toml
- tycho-indexer/src/substreams/mod.rs
StreamingFast will be enforcing compressed gRPC streams on substreams by the end of the month.
> feat: update substreams client to accept compressed messages

- tycho-client/src/rpc.rs
- tycho-indexer/src/services/rpc.rs
Tycho RPC follows the pattern of using POST endpoints with body parameters instead of GET endpoints with inline args.
> feat: make protocol system a POST endpoint

- tycho-client/src/stream.rs
The client errors with 'stale synchroniser' on start up if we set this to 2s. Defaulting this to 10s for Base pending a proper investigation on the handling of this setting and why it errors.
> fix: increase Base blocktime default

- .github/workflows/v2-build-and-deploy-branch.yaml
- tycho-client/src/rpc.rs
- tycho-indexer/src/services/mod.rs
This was causing bugs where the RPC was reusing connections that were already closed.
> fix: default RPC client and server to use HTTP/2

- tycho-indexer/src/services/deltas_buffer.rs
- tycho-indexer/src/services/rpc.rs
This fixes a bug that was occuring when someone was querying components with a TVL filter. In that case, any component in the buffer would be returned, even if it wasn't passing the tvl threshold requested.
> fix(rpc): correctly apply TVL filtering on `/protocol_component` requests

- tycho-core/src/models/protocol.rs
- tycho-core/src/storage.rs
- tycho-indexer/src/extractor/protocol_cache.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
- tycho-indexer/src/extractor/token_analysis_cron.rs
- tycho-indexer/src/services/rpc.rs
- tycho-indexer/src/testing.rs
- tycho-storage/src/postgres/cache.rs
- tycho-storage/src/postgres/protocol.rs
ISSUE: Currently our postgres gateway’s get_tokens fn optionally filters tokens by a min quality. For the most part this is all we need as all client interactions are concerned about highest quality/most relevant tokens only. However, our token analysis cronjob is interested in tokens with quality 6-10 only. A min quality filter alone is not sufficient here and results in the cronjob needlessly fetching excessive numbers of tokens from the DB only to skip analysing them.
> feat: update postgres gateway get_tokens quality filter to be ranged

- tycho-client/src/rpc.rs
Currently when an RPC call within the tycho-client fails, the client panics with:
`Fatal error: No response received` 
and the error that is logged is:
`ParseResponse("expected value at line 1 column 1")`.
This doesn't give us much info on what the problem was. With the changes in this PR we instead propagate a more informative error message. The client will now panic with (as an example):
`Failed to parse response: Unknown extractor: uniswap_v5` 
and log the error:
`ParseResponse("Unknown extractor: uniswap_v5")`.
> fix: propagate more meaningful RPC errors on the client

- docker-compose.yaml
This fix correctly map the volume to postgres, allowing it to be persistent between runs (unless the volume was deleted).
> chore(docker): fix volume config

- tycho-indexer/src/extractor/protobuf_deserialisation.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
Fixes and closes (https://github.com/propeller-heads/tycho-indexer/pull/283) 
Reason: EVM nodes gives us timestamps in seconds resolution. On sub-second blocks, we will have a conflict of multiple blocks with the same timestamp - causing bugs in the versioning system.
This solution appends n+1 microsecond for each block in a row (sequence size n) that is found with the same timestamp.
> feat: Handle blocks with same ts

- tycho-indexer/src/extractor/protocol_extractor.rs
Time remaining is sometimes buggy in its calculations and not emitted, as well as is unreliable (fluctuates a lot). For metric purposes it is better to monitor the rate at which it is syncing (blocks per min) and can calculate a more reliable time remaining using a moving average sync rate.
> refactor: emit sync rate metric instead of time remaining

- tycho-indexer/src/extractor/protocol_extractor.rs
This should fix the first report progress which currently reports false numbers
> refactor: stop emitting wrong syncing report on startup

- .github/workflows/release.yaml
- Cargo.lock
- tycho-indexer/Cargo.toml
We can't use the action because it errors on github dependencies in any workspace crate and we still depend on some cowswap crates for the token analyzer.
> ci: use cargo publish directly

- Cargo.lock
- release.config.js
Fixes Cargo.toml changes not being included in the git release commit which is automatically created by CI.
> fix: include workspace cargo toml in release config

- tycho-client-py/python/tycho_indexer_client/dto.py
This is because we don't return this for native protocols
> fix: Set default value for account_balances in BlockChanges model

- tycho-client/src/feed/synchronizer.rs
It is impossible to create test fixtures for FeedMessage atm because the attributes of Snapshot are not public
> fix: Make Snapshot attributes pub

- tycho-storage/src/postgres/schema.patch
This PR fixes a bug that was causing diesel print-schema to fail with `error applying hunk #1`
This bug was due to an outdated patch that was leading to conflicts when it was applied on top of the current migrations.
> chore: Update PostgreSQL schema patch to avoid conflicts on `diesel print-schema`

- tycho-indexer/src/services/ws.rs
Currently we would just stop the current actor on a websocket connection timeout and don't initiate the close handshake. This caused our metrics to become distorted as we were monitoring for closed connections and not dropped actors.
> fix: cleanly close ws connections on timeouts

- tycho-client/src/feed/component_tracker.rs
- tycho-common/src/storage.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
- tycho-indexer/src/main.rs
- tycho-indexer/src/testing.rs
- tycho-storage/migrations/2024-09-06_v0.16.2/down.sql
- tycho-storage/migrations/2024-09-19_transaction_cleanup/down.sql
- tycho-storage/src/postgres/cache.rs
- tycho-storage/src/postgres/chain.rs
- tycho-storage/src/postgres/contract.rs
- tycho-storage/src/postgres/mod.rs
- tycho-storage/src/postgres/orm.rs
- tycho-storage/src/postgres/protocol.rs
- tycho-storage/src/postgres/versioning.rs
Important decisions made:
- The versioning logic assumes data is inserted as block-scoped data. Therefore if the db has an update for a specific entity id at a given block, it is assumed all updates for that entity have been inserted at that block
- Due to the above, db data inserts/updates much be batched by block for dynamic/versioned tables. For the most part this is already how things are done on the indexer with one exception: new contracts.
- `upsert_contract` used to both insert a new contract and update the dynamic tables related to it. This makes it difficult to batch all changes done to the dynamic tables (slots, balance, code etc) into one db interaction as these same tables are also updated by `update_contracts`. Therefore `upsert_contract` was changed to `insert_contract` and …
> feat(versioning): drop new entries where newer versions already exist in the DB

- tycho-indexer/src/services/mod.rs
Instead of allowing only our docs, we allow every subdomains. This is needed for swagger UIs.
> feat: update CORS to allow all subdomains of `propellerheads.xyz`

- tycho-indexer/src/services/mod.rs
This is not needed and leads to a confusing swagger UI because it includes all servers on a chain specific Swagger so, so it can lead to confusion if you don't select the correct one (the one you used the swagger URL for).
> refactor: remove server URLs from OpenAPI definition

- tycho-client-py/src/main.rs
- tycho-client/README.md
- tycho-client/src/cli.rs
- tycho-client/src/deltas.rs
- tycho-client/src/feed/block_history.rs
- tycho-client/src/feed/component_tracker.rs
- tycho-client/src/feed/mod.rs
- tycho-client/src/feed/synchronizer.rs
- tycho-client/src/main.rs
- tycho-client/src/rpc.rs
- tycho-client/src/stream.rs
Improve error handling on the tycho-client. This is done by:
- removing all panics
- replacing them with warnings, or by raising appropriate errors
In a few cases it was decided to handle an error internally instead of propagate it. Such cases are:
- **Component Tracker**
Old behaviour: panics if you try fetch linked contracts for components that are not tracking
New behaviour: logs a warning and skips that component. Extended the docs to emphasise that it is expected for `start_tracking` or `initialise_components` to be called before fetching contracts for tracked components.
Bug fix: I also found a bug where if the ws client connection dropped and could not be re-established during the first half of the `state_sync` fn on the ProtocolStateSynchronizer (before the main loop), then we'd …
> feat(tycho-client): Remove panics from client

- tycho-indexer/src/substreams/stream.rs
"Tonic error" does not give us much information. Instead, the error code tells us if it is an internal error, unavailable connection etc.
> refactor(indexer): log error code for substream error metrics

- Dockerfile
Our main github workflow is failing due to dependencies that require rust version 1.82 and above.
> fix: update dockerfile rust version to 1.82

- tycho-storage/src/postgres/contract.rs
Currently, the docs for this function says "It will not update contract balance or contract code if they already exist though. Since a separate method exists for updating these related components." but it's still not ignoring conflicts. This commit fixes this.
> fix(postgres): add on_conflict_do_nothing to contract balance and code upserts

- tycho-client/src/feed/block_history.rs
Delayed extractors on start up were erroring with `Could not determine history` when they tried to catch up to the later blocks. This was due to the fact that on start-up, the BlockHistory created by the client has a gap for the unwitnessed blocks between the delayed extractor's block and the current block the other extractors are on. The `determine_block_position` function was then unable to determine where the catch-up blocks belonged within that gap.
We would also get a similar error if an extractor was delayed longer than the block history cache limit (currently 15 blocks).
Solution: 
1) improve the BlockHistory instantiation logic to skip detached blocks and ensure a fully connected history.
2) update `determine_block_position` to mark blocks older than the oldest in history as …
> fix(tycho-client): fix block position bug for delayed extractors on start up

- tycho-api.yaml
- tycho-indexer/src/extractor/protocol_extractor.rs
- tycho-indexer/src/main.rs
- tycho-storage/sql_scripts/remove_protocol_system.sh
- tycho-storage/src/postgres/cache.rs
- tycho-storage/src/postgres/chain.rs
- tycho-storage/src/postgres/contract.rs
- tycho-storage/src/postgres/protocol.rs
Currently the script doesn't delete contract code if the account is still used as a token. This commit fixes this.
> chore: fix deletion script

- tycho-api.yaml
- tycho-common/src/models/blockchain.rs
- tycho-common/src/storage.rs
- tycho-common/src/traits.rs
- tycho-ethereum/src/entrypoint_tracer/tracer.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
- tycho-indexer/src/main.rs
- tycho-storage/migrations/2025-04-09_dci_entry_points/down.sql
- tycho-storage/migrations/2025-04-09_dci_entry_points/up.sql
- tycho-storage/src/postgres/cache.rs
- tycho-storage/src/postgres/chain.rs
- tycho-storage/src/postgres/contract.rs
- tycho-storage/src/postgres/entry_point.rs
- tycho-storage/src/postgres/orm.rs
- tycho-storage/src/postgres/protocol.rs
- tycho-storage/src/postgres/schema.rs
This PR improves some logic related to `Entrypoints`, specifically:
- The main link with protocol components has been moved from the `EntrypointTracingParams` to the `Entrypoint`. The old link stays for debugging purposes but becomes optional
- The methods to insert and get `Entrypoint` and `EntrypointTracingParams` are now separated. This granularity was needed to be able to insert new data more with more flexibility from the extractor.
- Improved namings, change from `TracingData` to `TracingParams` for clarity. 
All these changes have previously been discussed [here](https://propellerswap.slack.com/archives/C05MPCJUQPM/p1747236824357709)
> refactor: improve Entrypoints methods on PostgresGateway

- tycho-storage/src/postgres/orm.rs
To ensure consistency with the application of pagination. Ordering by protocol system makes no sense as we filter for only 1 protocol system in the same query.
> fix: order protocol states query by protocol component

- tycho-common/src/models/blockchain.rs
- tycho-common/src/storage.rs
- tycho-storage/src/postgres/cache.rs
- tycho-storage/src/postgres/entry_point.rs
This commit updates the EntryPointGateway trait to include pagination parameters for the get_entry_points and get_entry_points_tracing_params methods, returning results wrapped in a WithTotal struct. This is needed by the RPC methods.
> feat: add pagination to EntryPointGateway

- docker-compose.yaml
- tycho-storage/README.md
- tycho-storage/src/postgres/orm.rs
Still use the old (very fast) query to get most of the entries. For the entries that are missing, look for them in the archived tables (this query is much slower)
I used SQL `EXPLAIN ANALYSE` to compare the queries and:
- the query that uses the `valid_to.eq(MAX_TS)` takes:
````
Planning Time: 0.142 ms     
Execution Time: 0.027 ms    
````
- the one that uses the `distinct` takes:
````
Planning Time: 10.915 ms  
Execution Time: 0.738 ms  
````
> chore: Optimized DB queries

- tycho-client/src/deltas.rs
- tycho-client/src/feed/component_tracker.rs
- tycho-client/src/feed/synchronizer.rs
- tycho-client/src/rpc.rs
- tycho-common/src/dto.rs
- tycho-common/src/models/blockchain.rs
- tycho-indexer/src/extractor/models.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
This PR covers the following:
- extends RPCClient to include `get_traced_entry_points` endpoint and support auto-pagination
- extends the emitted message models to include all entrypoint data (entrypoints, params and traces)
- extends the component_tracker to track entrypoints and monitor which contracts to filter accordingly
- extends the client's protocol synchronizer to use the updated component_tracker and entrypoint data where necessary
> feat: extend tycho-client to handle dci data

- tycho-indexer/src/extractor/dynamic_contract_indexer/cache.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/dci.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/mod.rs
- tycho-indexer/src/extractor/mod.rs
- tycho-indexer/src/extractor/runner.rs
- tycho-indexer/src/testing.rs
This PR implements the logic needed by DCI to properly deal with chain reorgs. 
It moves all dci related files into a "folder module".
We added a helper structs which is essentially a wrapper around HashMap. This struct helps to efficiently keep track of the permanent and pending state and provides functions to revert the cache state to a previous state.
**Review commit by commit suggested**
> feat(dci): add revert logic

- tycho-common/src/dto.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
- tycho-storage/src/postgres/contract.rs
When an account is added as a token, no creation_tx is assigned to the account entry. Since the `get_contracts` DB gateway function uses the linked `creation_tx` to apply versioning to, if it is set to NULL we will always filter it out when we apply versioning. Therefore we should only apply versioning to account entries that have a creation_tx specified.
Done in this PR:
- do not filter out accounts that have no `creation_tx`
- optimise the queries: 
- remove transaction table join (creation tx isn't always available and is misleading for DCI added contracts as they are linked to the transaction where DCI detected them and not where the contract was created)
- improve count query (and skip if no pagination was applied)
> fix(storage): fix bug that filters out contracts missing a creation_tx

- tycho-indexer/src/extractor/dynamic_contract_indexer/component_metadata.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/euler/metadata_generator.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/euler/mod.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/hook_dci.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/mod.rs
This PR adds metadata generator for Euler Swap
TODOs:
> feat(hook-support): implement metadata generator for Euler Swap

- tycho-client/src/feed/block_history.rs
- tycho-client/src/feed/mod.rs
- tycho-client/src/feed/synchronizer.rs
- tycho-common/src/lib.rs
- tycho-common/src/simulation/errors.rs
- tycho-common/src/simulation/mod.rs
- tycho-common/src/simulation/protocol_sim.rs
Done:
- Generalise Header by creating a HeaderLike trait. Rename Header to BlockHeader
- Move ProtocolSim from simulation (and also GetAmountOutResult, Balances, SimulationError and TransitionError)
This is needed for RFQs where we only need the timestamp
Corresponding PRs:
- https://github.com/propeller-heads/tycho-simulation/pull/257
- https://github.com/propeller-heads/tycho-execution/pull/240
> feat: Generalise Header and add ProtocolSim

- tycho-indexer/src/extractor/dynamic_contract_indexer/component_metadata.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/euler/metadata_generator.rs
This PR adds a customizable way to decode values returned by RPC/API calls. This will need to be implemented for each hook protocol. 
It also adds the first implementation of this trait for `EulerSwap`
> feat: add metadata response parser

- tycho-storage/src/postgres/orm.rs
- tycho-storage/src/postgres/versioning.rs
The query was too slow and it's not necessary for ProtocolStates, since only one extractor should be able to mutate a ProtocolState.
> fix: Remove missing state query on versioning

- tycho-storage/migrations/2025-07-21_index_protocol_components/up.sql
This PR adds a missing "IF NOT EXISTS" in the new migration, this helps in case the index has already been manually created
> refactor: properly handle index cration in migrations

- postgres.Dockerfile
- tycho-storage/src/postgres/entry_point.rs
So far we were only considering the latest tracing result. Now we're merging new results with old data on inserts, this will allow us to keep a more complete list of possibly used slots.
> feat: merge tracing results on inserts

- Cargo.lock
- tycho-ethereum/Cargo.toml
- tycho-ethereum/src/entrypoint_tracer/tracer.rs
This PR improves the tracer:
- Removes `ethers-rs` usage. Only use alloy
- Batch the two RPC call together
> refactor: miscellaneous tracer improvements

- tycho-common/src/traits.rs
- tycho-ethereum/src/account_extractor/contract.rs
- tycho-ethereum/src/entrypoint_tracer/mod.rs
- tycho-ethereum/src/entrypoint_tracer/tracer.rs
- tycho-ethereum/src/lib.rs
- tycho-ethereum/src/token_analyzer/rpc_client.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/dci.rs
- tycho-indexer/src/services/rpc.rs
We want DCI to differentiate tracing errors between recoverable and unrecoverable.
For example if it's a connection issue with the RPC, we should retry the tracing later. But if it's an EVM execution failure, it means the entrypoint is wrong and we don't need to retry.
This PR is the first step toward this. It improves the tracer to return a different error if the tracing fails because of a EVM execution failure.
Additionally, it refactors the tracer to return specific error per request instead of batch scoped error.
> feat: Add new error type for tracing execution failure

- tycho-indexer/src/extractor/dynamic_contract_indexer/cache.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/dci.rs
In some cases we need a full cache lookup. For example when getting retriggers or tracked slots we want to return all the elements and not only the last one.
This commit adds a `get_all` function on the `VersionedCache` to allow for this. We now use it instead of a simple `.get()` when needed inside DCI implementation
> fix: correctly get all values from cache when needed.

- tycho-common/src/models/blockchain.rs
- tycho-common/src/storage.rs
- tycho-ethereum/src/account_extractor/contract.rs
- tycho-ethereum/src/entrypoint_tracer/tracer.rs
- tycho-ethereum/src/lib.rs
- tycho-ethereum/src/token_analyzer/rpc_client.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/cache.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/dci.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/hook_dci.rs
- tycho-indexer/src/extractor/runner.rs
- tycho-indexer/src/services/deltas_buffer.rs
This PR resolves [ENG-4707](https://propeller-heads.atlassian.net/jira/software/projects/ENG/boards/24/backlog?label=Cairoline&selectedIssue=ENG-4707) and [ENG-4844](https://propeller-heads.atlassian.net/jira/software/projects/ENG/boards/24/backlog?label=Cairoline&selectedIssue=ENG-4844).
We've added a configurable retry logic inside the ethereum tracer and added the logic in DCI and its cache to emit the "paused" state attribute for all the related components when a tracing fails after all the retries. 
[ENG-4707]: https://propeller-heads.atlassian.net/browse/ENG-4707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-4844]: https://propeller-heads.atlassian.net/browse/ENG-4844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> feat: implement pausing component in DCI

- tycho-client/src/deltas.rs
- tycho-client/src/feed/synchronizer.rs
- tycho-indexer/src/services/deltas_buffer.rs
Automatically unsubscribes from a protocol if client can't keep up with message flow. This will force the client to reconnect which clears the buffer and thus gives the client a chance to recover. This behaviour is better compared to dropping the message with a warning which most certainly leads to corrupted state.
> fix: handle buffer overflow in client

- Cargo.lock
- tycho-client/Cargo.toml
- tycho-client/src/feed/synchronizer.rs
- tycho-client/src/rpc.rs
This avoids crashing if one rpc requests fails or gets rate limited. Once we correctly return a retry-after header from the server, the client will respect it and requests will wait until then.
> feat: Retry on transient rpc error.

- tycho-ethereum/Cargo.toml
- tycho-ethereum/src/account_extractor/contract.rs
We were getting `invalid URL, scheme is not http` errors after bumping alloy on this commit: https://github.com/propeller-heads/tycho-indexer/pull/698/commits/847177d80e45c512820128d7590e58085b10b9bd
Culprit was that alloy removed the reqwest-default-tls from the default features on this commit: https://github.com/alloy-rs/alloy/pull/2865/files#diff-680e1376f52cad37f180f99cac82995eb05e5c3401aa4ff9a7d899ec534afa0f
> fix: Fix TLS not working after bumping Alloy version

- tycho-common/src/dto.rs
We added a custom deserialization that defaults offset to 0 when it's missing. This is fine because it's not used by tycho-simulation.
This is needed to smoothly update prod with the new release without having to sync with all clients. They can now update their tycho-client version before and it will automatically support both old and new release.
We can remove this once everything is more stable.
> fix: make `TracingResult` deserialization backward compatible

- tycho-indexer/src/extractor/runner.rs
- tycho-indexer/src/main.rs
- drive `SubstreamsArgs` through the indexing task builder so CLI flags populate extractor auth
- update ExtractorBuilder::new to take the token directly rather than re-reading `SUBSTREAMS_API_TOKEN` from the environment
> fix: support configuring `substreams_api_token` via CLI and instead of only env variables

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/for-solvers/execution/README.md
- tycho-client-py/pyproject.toml
- tycho-indexer/src/cli.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/hook_dci.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/hooks_dci_setup.rs
- tycho-indexer/src/extractor/dynamic_contract_indexer/rpc_metadata_provider.rs
- tycho-indexer/src/extractor/protocol_extractor.rs
- tycho-indexer/src/extractor/reorg_buffer.rs
- tycho-indexer/src/extractor/runner.rs
- tycho-indexer/src/main.rs
- tycho-indexer/src/services/deltas_buffer.rs
- add a CLI config controlling how many finalized blocks must accumulate before we flush to Postgres (default 128, matching Ethereum finality)
- refactor `ProtocolExtractor` to buffer messages via a helper that drains/commits only once the batch size is met, and capture the committed watermark consistently
- extend the reorg buffer with count helpers plus targeted unit tests to cover the new batching
behaviour
> feat: add configurable batch commit threshold for extractors
